language: java
sudo: false
script: mvn clean verify
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc -out $GPG_DIR/pubring.gpg -d
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc -out $GPG_DIR/secring.gpg -d
  - chmod +x "$GPG_DIR/publish.sh"
  - "$GPG_DIR/publish.sh"
env:
  global:
  - GPG_DIR="`pwd`/deploy"
